# Generated by Django 4.2.20 on 2025-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_token', models.CharField(max_length=512)),
                ('workspace_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_token', models.CharField(max_length=512)),
                ('calendar_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MicrosoftCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_token', models.CharField(max_length=512)),
                ('calendar_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_token', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TrelloIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trello_token', models.CharField(max_length=512)),
                ('board_id', models.CharField(max_length=255)),
            ],
        ),
    ]
