# Generated by Django 5.2 on 2025-04-21 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_workspace_type",
                    models.CharField(
                        choices=[
                            ("DESK", "Desk"),
                            ("ROOM", "Room"),
                            ("SPACE", "Open Space"),
                        ],
                        default="DESK",
                        max_length=50,
                    ),
                ),
                ("receive_email_notifications", models.BooleanField(default=True)),
                ("receive_booking_reminders", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
