# Generated by Django 5.2 on 2025-04-16 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('usage', 'Usage Report'), ('history', 'Booking History'), ('custom', 'Custom Query')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
