# Generated by Django 4.2.20 on 2025-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('usage', 'Usage Report'), ('history', 'Booking History'), ('custom', 'Custom Query')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=50)),
            ],
        ),
    ]
