# Generated by Django 4.2.20 on 2025-04-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('svg_map', models.TextField(help_text='SVG or base64 encoded floor map')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='workspace_booking.location')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('config_type', models.CharField(choices=[('boardroom', 'Boardroom'), ('classroom', 'Classroom'), ('pod', 'Pod'), ('open_desk', 'Open Desk')], max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('live_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='workspace_management.floorplan')),
            ],
        ),
    ]
